### ISSUE TITLE
README to mention caveat for Nx CLI based Angular projects

### ISSUE THREAD

**Issue by nalaka** [ngneat/tailwind#10]
According to [nrwl/nx issue #2861](https://github.com/nrwl/nx/issues/2861), `nx add` doesn't work with Nx workspaces using the Nx CLI (as opposed to the Angular CLI).

it'd be useful to mention this in the README.

**Comment by nartc** [comment]
Thanks for reporting. I do have plan to put this in the README as discussed here #6
