### ISSUE TITLE
Purge safelist don't work

### ISSUE THREAD

**Issue by jeanfern** [ngneat/tailwind#100]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Once I have to concatenate class names to apply some colors to my component and Tailwind purge don't like it by default (It''s on their doc), I have three possible solutions:

- **Add the full class instead concatenate them**
_Not viable for that case_
- **Declarate them on component SASS just to they don't be purged**
_Workaround, but too much worky to bigger projects_
- **Add them to the Tailwind purge safelist**
_Looks like the purge configs on tailwind.config.js doesn't work particulary with Angular and testing it I guess the entire purge settings aren't working._

I am testing Vue, React and Angular with same study case project. Safelist worked with them.
Following details:

```js
//tailwind.config.js

const { guessProductionMode } = require("@ngneat/tailwind");

module.exports = {
    prefix: '',
    mode: 'jit',
    purge: {
      // I suspect purge config aren't work at all, not just the safelist
      // once I tried set it off using enable: false here and I don't work as well
      enable: true, // set false to test it
      content: [
        './src/**/*.{html,ts,css,scss,sass,less,styl}',
      ],
      // I have tried:
      // safelist: ['regex'],
      // whitelist: ['regex'],
      // safelist: { standard: [ 'regex' ] }
      // but looks like doesn't matter, safelist has been ignored. 
      safelist: ['\w*-pokemon-\w*']
    },
    darkMode: 'class', // or 'media' or 'class'
    theme: {
      extend: {
        colors: {
          pokemon: {
            bug: '#9DC130',
            dark: '#5F606D',
            dragon: '#0773C7',
            electric: '#EDD53F',
            fairy: '#EF97E6',
            fight: '#D94256',
            fire: '#F8A54F',
            flying: '#9BB4E8',
            ghost: '#6970C5',
            grass: '#5DBE62',
            ground: '#D78555',
            ice: '#7ED4C9',
            normal: '#9A9DA1',
            poison: '#B563CE',
            psychic: '#F87C7A',
            rock: '#CEC18C',
            steel: '#5596A4',
            water: '#559EDF',
          },
        },
      },
    },
    variants: {
      extend: {},
    },
    plugins: [
      require('@tailwindcss/aspect-ratio'),
      require('@tailwindcss/forms'),
      require('@tailwindcss/line-clamp'),
      require('@tailwindcss/typography')
    ],
};
```

## Environment
```js
// package.json
{
  "name": "Pokedex - Studying Angular + Tailwind",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.11",
    "@angular/common": "~11.2.11",
    "@angular/compiler": "~11.2.11",
    "@angular/core": "~11.2.11",
    "@angular/forms": "~11.2.11",
    "@angular/platform-browser": "~11.2.11",
    "@angular/platform-browser-dynamic": "~11.2.11",
    "@angular/router": "~11.2.11",
    "@ngneat/tailwind": "^7.0.3",
    "angular-svg-icon": "^11.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.10",
    "@angular/cli": "~11.2.10",
    "@angular/compiler-cli": "~11.2.11",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/forms": "0.3.2",
    "@tailwindcss/line-clamp": "0.2.0",
    "@tailwindcss/typography": "0.4.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "tailwindcss": "2.1.2",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}
```

**Comment by tomhughes-invento** [comment]
purgecss options are not supported in jit mode in tailwind (this is documented on tailwind's end, as their jit compiler no longer uses purgecss). The only way to add support back currently is to have a txt file somewhere in your project that has all the classes you want to keep, then list that file in your purge paths, e.g.

```javascript
module.exports = {
    mode: 'jit',
    purge: {
      content: [
        './src/**/*.{html,ts,css,scss,sass,less,styl}',
        './safelist.txt'
      ],
  }
}
```

Unfortunately means you have to manually write out all your classes too, so may not be viable in your case if you don't know every class you want to save (in the case of 1 of my projects I wrote a quick node script that generated the file for me based on some json influenced by the regex originally being used).

Until Tailwind officially re-support safelists (including regex matching) you have to either not use jit (in which case the regular compiler still uses & supports purgecss), or work around it with their suggestion of a txt file containing all the classes you want to save.

**Comment by cp-jeanfern** [comment]
Ah so the problem is not with "Purge" is the "JIT" mode, now I see.
That is fine, at least I know that I was not crazy. Haha.

> purgecss options are not supported in jit mode in tailwind (this is documented on tailwind's end, as their jit compiler no longer uses purgecss). The only way to add support back currently is to have a txt file somewhere in your project that has all the classes you want to keep, then list that file in your purge paths, e.g.
> 
> ```js
> module.exports = {
>     mode: 'jit',
>     purge: {
>       content: [
>         './src/**/*.{html,ts,css,scss,sass,less,styl}',
>         './safelist.txt'
>       ],
>   }
> }
> ```
> 
> Unfortunately means you have to manually write out all your classes too, so may not be viable in your case if you don't know every class you want to save (in the case of 1 of my projects I wrote a quick node script that generated the file for me based on some json influenced by the regex originally being used).
> 
> Until Tailwind officially re-support safelists (including regex matching) you have to either not use jit (in which case the regular compiler still uses & supports purgecss), or work around it with their suggestion of a txt file containing all the classes you want to save.

**Comment by vltansky** [comment]
Guess this issue can be closed, as this one is not a `ngneat/tailwind` bug, but Tailwindcss itself :)

**Comment by jschuur** [comment]
> Until Tailwind officially re-support safelists (including regex matching) you have to either not use jit (in which case the regular compiler still uses & supports purgecss), or work around it with their suggestion of a txt file containing all the classes you want to save.

The approach I took was to disable JIT only for production. From my `module.exports` in `tailwind.config.js`:

```
  mode: process.env.NODE_ENV === 'production' ? undefined : 'jit',
```
