### ISSUE TITLE
Tailwind in Angular Storybook

### ISSUE THREAD

**Issue by ignaciomandagaran** [ngneat/tailwind#103]
## Hi everyone! 

I'm working on an Angular project where Tailwind CSS was successfully integrated thanks to this awesome schematic.
Now I want to integrate it into our Angular [Storybook](https://storybook.js.org/) as well.

#### How can I do that? Any idea? 🙏🏼

_Originally posted by @ignaciomandagaran in https://github.com/ngneat/tailwind/discussions/82_

**Comment by kingjordan** [comment]
i would take a look at the nx workspace from https://nx.dev/ and how they add storybook.  Ultimately I suggest using this workspace to create your app and then workspace can easily add storybook.

**Comment by ignaciomandagaran** [comment]
Solved! Only add this in the .storybook/main.js:

```
//.storybook/main.js

const { addTailwindPlugin } = require("@ngneat/tailwind");
const tailwindConfig = require("../tailwind.config");

module.exports = {
  stories:[
    ...
  ],
  addons: [
    ...
  ],
  webpackFinal: async (config) => {
    addTailwindPlugin({
      webpackConfig: config,
      tailwindConfig,
      patchComponentsStyles: true
    });
    return config;
  }
}
```
![Screen Shot 2021-07-01 at 12 20 46](https://user-images.githubusercontent.com/58785180/124149279-cfa2bb80-da66-11eb-88f9-304369c18759.png)

😉
