### ISSUE TITLE
Tailwind is fired multiple times. 

### ISSUE THREAD

**Issue by samartomar** [ngneat/tailwind#104]
**Is your feature request related to a problem? Please describe.**

I am using NX and have big setup almost 120+ Libs and 12 Apps 
After adding tailwind every thing went down hill build time increased by 10-12 times. main project build went from 40sec to 1min 32sec min. 

What i found is use of new cli feature to find tailwind.config. might be root cause. now matter weather tailwind is needed or not it's getting fired. for my main project tailwind.config fired 180 times. 

**Describe the solution you'd like**
Control on tailwind only triggers for that component in NX vs overall monoreport or workspace. 

**Describe alternatives you've considered**
Thingking going back for old school with webpack might be only solution. but i liked what you have done wanted to see if this is something can be build with ngneat. 

**Additional context**

**Comment by vltansky** [comment]
Which Angular & ngneat/tailwind version are you using?
Latest `ngneat/tailwind` leverages Angular CLI built-in support of tailwind. So if there is a bug - it sounds to me like an Angular CLI bug.
@nartc am I missing something?

**Comment by samartomar** [comment]
using Angular 12. NX 12.3.3 my finding is having tailwind config at top is ok if you have 1-2 projects. 
in my example i have 14  project 140 Libs Tailwind instalation made performance worst. finally i put tailwind config in prj folder where it is needed and removed from top solved issue.

**Comment by samartomar** [comment]
Also seems angular cli has 2 times generation issue anyway
