### ISSUE TITLE
Tailwind does not apply custom colors

### ISSUE THREAD

**Issue by Eventyret** [ngneat/tailwind#105]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
It seems that tailwind is not registering new colors?
```
 theme: {
    extend: {
      colors: {
        bob: '#21FEB7'
      }
    }
  },
```
☝️ Added as example the color "bob" vscode tailwind extension picks this up and shows the following
```
.bg-bob {
  --tw-bg-opacity: 1;
  background-color: rgba(33, 254, 183, var(--tw-bg-opacity));
}
```
When viewing in the browser it will be white and not applied. Might be for angular ?
Using @ngeat/tailwind 7 with JIT

## Expected behavior

Expected the correct color to be applied

## Minimal reproduction of the problem with instructions
- Add the above code to `tailwind.config.js`
- Create any div to test and use the class `flex h-screen bg-bob`
-  
For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem

## What is the motivation / use case for changing the behavior?

Adding custom branding colors
## Environment

<pre><code>
Angular version: 11.2.12

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.x  
- Platform:  Mac 

Others:

</code></pre>

Any other questions that I can help with or missing feedback please let me know

**Comment by AlexanderOpran** [comment]
Sadly I do not think this is related to `ngneat/tailwind`. We don't use it (just barebone tailwind) and we have this issue as well. It's most likely something related to Angular itself (even though we are using fixed versions - so probably a dependency of a dependency that does some bad things).

This also occurs without using JIT and it doesn't matter what Tailwind version we are using. Issue being that the opacity variable is declared but it is not used in the color itself. If it helps, it our case it only occurs when doing a production build.

**Comment by AlexanderOpran** [comment]
This is what is causing the issues: https://github.com/cssnano/cssnano/commit/a7f0be4acc640aab89cace53a720b3d59b6f7b4f

**Comment by Eventyret** [comment]
Thanks for checking it out @AlexanderOpran , at least we know it's not  `ngneat/tailwind` so feel free to close this.
Then it's just waiting to see when it gets fixed from the bugs posted

Again thank you @AlexanderOpran  👍

**Comment by AlexanderOpran** [comment]
For now the it was reverted to the older version. Feel free to do a fresh `npm install` at it should work.

**Comment by AlexanderOpran** [comment]
A hotfix was made: https://github.com/cssnano/cssnano/commit/c722aeff0c8e3b3effd561a997e5a0b279d3aab6

**Comment by vltansky** [comment]
Closing this as not relevant for `ngneat/taiwlind`. Thanks for checking this @AlexanderOpran!
