### ISSUE TITLE
Support Angular V12

### ISSUE THREAD

**Issue by dianjuar** [ngneat/tailwind#106]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently con Angular V12, the schematic launches a series of warnings about the usage of and `id` instead of and `$id` on some "schemas"

![image](https://user-images.githubusercontent.com/7026066/119237319-1066f680-baf1-11eb-91be-c14e525263d7.png)

## Expected behavior

No warnings on the schematic use.

## Minimal reproduction of the problem with instructions

Just do an `npx ng add @ngneat/tailwind` on an Angular V12 project

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem

## What is the motivation / use case for changing the behavior?

A clean installation without warnings

## Environment

<pre><code>
Angular version: 12.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 14.17.0  
- Platform: Mac 

Others:

</code></pre>

**Comment by dianjuar** [comment]
To solve this I firmly beleave that is just to change the `id` for `$id` on your schema definitions

- [libs/tailwind/src/schematics/ng-add/schema.json](https://github.com/ngneat/tailwind/blob/ba1f9c94fd51c7b1492c0c572a6e67499a5d70f6/libs/tailwind/src/schematics/ng-add/schema.json)
- [libs/tailwind/src/schematics/nx-setup/schema.json](https://github.com/ngneat/tailwind/blob/ba1f9c94fd51c7b1492c0c572a6e67499a5d70f6/libs/tailwind/src/schematics/nx-setup/schema.json)

And maybe update `@angular-devkit` to a version that doesn't use `id` on the following schematics, (I couldn't determine which version is being used):
- [ibs/tailwind/collection.json](https://github.com/ngneat/tailwind/blob/ba1f9c94fd51c7b1492c0c572a6e67499a5d70f6/libs/tailwind/builders.json)
- [libs/tailwind/collection.json](https://github.com/ngneat/tailwind/blob/ba1f9c94fd51c7b1492c0c572a6e67499a5d70f6/libs/tailwind/collection.json)

---

I recently solved this issue on a builder that I maintain [ngx-deploy-npm](https://github.com/bikecoders/ngx-deploy-npm/pull/63/files)

**Comment by Polyterative** [comment]
Would really appreciate some news on this

**Comment by dianjuar** [comment]
> Would really appreciate some news on this

@Polyterative In my case, it doesn't affect the execution of the schematic, it's just annoying as a developer to have a confusing warning that doesn't have anything related to the operation you want to perform. 

I believe that you can move along without the fix, it would not affect the end result
