### ISSUE TITLE
postcss-import issue using tilda

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/tailwind#11]
When using the default CLI we can use `~` to import styles from `node_modules`. For example:

```scss
// some.component.scss
@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-alpine.css";
```

However, when moving to postcss, it doesn't work anymore. It's something related to the `postcss-import` plugin. I don't have the time to investigate. 

@nartc, it'll be great if you can solve it.

**Comment by DimiDeKerf** [comment]
I was struggling with combining Tailwind and Angular Material, more specifically with the import `@import '~@angular/material/theming';`

Apparently the tilda is specific for the css-loader of Webpack to target the `node_modules`, whereas PostCSS will resolve these imports automatically. So if you drop the tilda, the import should work again. Hopefully this helps you further with the investigation.

Thanks btw for the schematics, it's very convenient!

**Comment by nartc** [comment]
@DimiDeKerf Thanks for the comment
@NetanelBasal 
Before working on this schematics, I’ve already run into this problem. And as both of you have said, it’s related to postcsd-import. At some point, I stopped diving into this issue and started using a workaround which is relative path import + including the extension (.css, .scss, etc...)

We can maybe list that as a workaround in the readme for now (if we can gather more use-cases, like the case of angular/material, that’d be great). 

As of the moment, I’m in the middle of a job transitioning and have no computer so I’ll get back to investigating this issue more when I get a new computer.

**Comment by NetanelBasal** [comment]
@DimiDeKerf I already tried it, and it doesn't work.

@nartc no problem. If I find the time, I'll help with that.

**Comment by NetanelBasal** [comment]
Ok, so we need to remove the `tilda` and add `ViewEncapsulation.None`
