### ISSUE TITLE
After updating to Angular 12, JIT not watching for changes in files deeper than the app.component.html file.

### ISSUE THREAD

**Issue by harvanchik** [ngneat/tailwind#117]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Upon changes a tailwind class in the HTML, the styles are not updated to reflect the addition of the class.

## Expected behavior
The css classes should be added to the styles.

## Minimal reproduction of the problem with instructions

package.json:
<pre><code>
{
  "name": "my-app",
  "version": "0.0.0",
  "scripts": {
    "start-dev": "ng serve --open",
    "build": "ng build",
    "updates": "ncu"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/cdk": "^12.2.5",
    "@angular/common": "~12.2.5",
    "@angular/compiler": "~12.2.5",
    "@angular/core": "~12.2.5",
    "@angular/forms": "~12.2.5",
    "@angular/material": "^12.2.5",
    "@angular/platform-browser": "~12.2.5",
    "@angular/platform-browser-dynamic": "~12.2.5",
    "@angular/router": "~12.2.5",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fortawesome/angular-fontawesome": "^0.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@ngneat/tailwind": "^7.0.3",
    "@swimlane/ngx-datatable": "^19.0.0",
    "angular-gridster2": "^12.1.0",
    "ngx-dates-picker": "^9.0.2",
    "ngx-toastr": "^14.1.2",
    "npm-check-updates": "^11.8.5",
    "rxjs": "~7.3.0",
    "tslib": "^2.3.1",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.5",
    "@angular/cli": "~12.2.5",
    "@angular/compiler-cli": "~12.2.5",
    "@tailwindcss/forms": "0.3.3",
    "@tailwindcss/line-clamp": "0.2.1",
    "@types/jasmine": "~3.9.0",
    "@types/node": "^16.7.13",
    "autoprefixer": "^10.3.4",
    "codelyzer": "^6.0.2",
    "headlessui-angular": "^0.0.5",
    "jasmine-core": "~3.9.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "~7.0.0",
    "tailwindcss": "2.2.14",
    "ts-node": "~10.2.1",
    "tslint": "~6.1.0",
    "typescript": "^4.3.5"
  }
}

</code></pre>

tailwind.config.js
<pre><code>
const colors = require('tailwindcss/colors');

module.exports = {
    prefix: '',
    mode: 'jit',
    purge: {
        content: [
            './src/**/*.{html,ts,js}',
        ]
    },
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#70c636',
                    50: '#f1f9eb',
                    100: '#e2f4d7',
                    200: '#c6e8af',
                    300: '#a9dd86',
                    400: '#8dd15e',
                    500: '#70c636',
                    600: '#5a9e2b',
                    700: '#437720',
                    800: '#2d4f16',
                    900: '#16280b'
                },
                secondary: {
                    DEFAULT: '#c9ebf4',
                    50: '#f4fbfd',
                    100: '#eff9fc',
                    200: '#e4f5fa',
                    300: '#d9f1f7',
                    400: '#ceedf5',
                    500: '#c9ebf4',
                    600: '#b5d4dc',
                    700: '#8da5ab',
                    800: '#65767a',
                    900: '#3c4649'
                },
            },
            fontFamily: {
                'sans': ["'IBM Plex Sans'", 'san-serif']
            }
        },
        screens: {
            'sm': { 'max': '599px' },

            'md': { 'min': '599px' },

            'lg': { 'min': '900px' },

            'xl': { 'min': '1200px' },

            '2xl': { 'min': '1800px' }

        }
    },
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/line-clamp')],
};
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
Chromium (Desktop) version 93.0.4577.63
 
For Tooling issues:
- Node version: 14.17.3  
- Platform: Windows 10 

Others:
IDE: VS Code

</code></pre>

**Comment by harvanchik** [comment]
I have also tied setting the env. variable, but still no luck.

<pre><code>{
  ...
  "scripts": {
    "start-dev": "cross-env NODE_ENV=development ng serve --open",
    "build": "ng build",
    "updates": "ncu"
  },
  ...
}
</code></pre>

**Comment by harvanchik** [comment]
The console also says that the project is watching for changes.
![image](https://user-images.githubusercontent.com/66141166/132572642-2e672d88-d5da-457a-82df-5601aa75cd21.png)

**Comment by harvanchik** [comment]
This appears to be a TailwindCSS issue.  Follow this issue [here](https://github.com/tailwindlabs/tailwindcss/issues/5459).

Closing unless this needs reopening.

**Comment by harvanchik** [comment]
Reopining because Tailwind no longer appears to be the problem.

**Comment by harvanchik** [comment]
I had another project that I just updated from Angular 11 to Angular 12, and not this issue has been introduced in that project.  Looks like something changed with Angular 12 that is causing JIT to fail searching for styles.  Oddly, the `app.component.html` still sees the changes, but any other file nested deeper than that does not.

**Comment by harvanchik** [comment]
Okay, this might just be an Angular thing now.  Looks like Tailwind is supported out of the box by Angular 12+ now; although JIT might not be supported (which is dumb).

**Comment by SamanthaAdrichem** [comment]
Did you create an angular ticket?
