### ISSUE TITLE
Error: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by amguruprasath** [ngneat/tailwind#13]
## I'm submitting a bug report on my new angular 10 project, I get the following error 
**ERROR in Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: true is not a PostCSS plugin**
[Please clone the rep to check](https://github.com/amguruprasath/ngneat-issue)

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Minimal reproduction of the problem with instructions

1. Generate new angular project (~10.1.6)
2. `ng add @ngneat/tailwind`
3. `ng serve`

## Environment

<pre><code>
Angular version: 10.1.6

Browser:
- [x ] Chrome (desktop) version 86.0.4240.75 

For Tooling issues:
- Node version: v12.19.0
- Platform:   Windows 10

**Comment by nartc** [comment]
Thank you for reporting. Fix with 1.0.7
