### ISSUE TITLE
Why was the postcss-import added?

### ISSUE THREAD

**Issue by shaharkazaz** [ngneat/tailwind#15]
What was the reason the `postcss-import` plugin was added? seems to be working without it as well.

**Comment by nartc** [comment]
Without `postcss-import`, importing other style files won't have Tailwind `directives` applied. Check the following case:

```scss
// common.scss
h1 {
   @apply text-5xl; // 3rem
}
```

```scss
// styles.scss
@import 'tailwindcss/base';
@import 'common';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
/* You can add global styles to this file, and also import other style files */
```

The `@apply text-5xl;` won't be applied without `postcss-import`. However with `postcss-import`, the importing syntax gets complicated (and contains caveats surrounding them):

```scss
// styles.scss
@import 'tailwindcss/base';
// @import 'common'; won't work with postcss-import
@import './common.scss'; // works with postcss-import
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
/* You can add global styles to this file, and also import other style files */
```


Although without `postcss-import`, it does remove all the caveats around importing external (3rd party libs like Angular Material) stylesheets. What would be your suggestions? I'll be adding this to the README regardless

**Comment by shaharkazaz** [comment]
@nartc I have a problem importing a mixin scss file from a 3rd party lib that depends on other internal scss files.
I'm trying to import [this mixin](https://www.ag-grid.com/javascript-grid-themes-customising/#setting-parameters-using-sass) from ag-grid but when the `postcss-import` is present it fails.
```
Error: Failed to find './mixins/ag-grid-mixins'
```

**Comment by nartc** [comment]
@shaharkazaz Yup. I'll play around with some more use-cases regarding components styles to see if it's justified to drop `postcss-import` altogether.

As of right now, without `postcss-import`, the above case with importing a `common.scss` in `styles.scss` won't crash the build but won't have Tailwind directives applied if there are directives usage in `common.scss`.

**Comment by shaharkazaz** [comment]
@nartc Share your findings once you have some 🙂

**Comment by vltansky** [comment]
@shaharkazaz @nartc did you find any solution?

**Comment by shaharkazaz** [comment]
@vltansky I'm not using the `postcss-import` since I don't use the `@apply` so that works for me.
@nartc any findings on this?

**Comment by vltansky** [comment]
@shaharkazaz @nartc 
I've succeeded to make it work according to answers in this issue: https://github.com/angular/angular-cli/issues/8427
As Angular 11.0.5 uses Postcss 8 we don't need to install PostCSS 8, postcss-import, autoprefixer and etc. as angular already have it.

So after `ng add @ngneat/tailwind` I've removed all node modules that we don't need anymore:
```
$ npm uninstall postcss postcss-loader postcss-import autoprefixer postcss-scss -D
```
and according to https://github.com/angular/angular-cli/issues/8427#issuecomment-744678690 with small modifications changed `webpack.config.js` to:
```
module.exports = (config) => {
  const isProd = config.mode === "production";
  const tailwindConfig = require("./tailwind.config.js")(isProd);
  
  const globalStylesPostcssLoaderOptions = config.module.rules
  .find((r) => r.include && r.test && r.test.toString().includes('\\.scss$'))
  .use.find((u) => u.loader && u.loader.includes('postcss-loader')).options;

  const globalStylesPostcssOptionsCreator = globalStylesPostcssLoaderOptions.postcssOptions;

  globalStylesPostcssLoaderOptions.postcssOptions = (loader) => {
    const postcssOptions = globalStylesPostcssOptionsCreator(loader);
    postcssOptions.plugins.splice(postcssOptions.plugins.length - 1, 0, require('tailwindcss')(tailwindConfig));

    return postcssOptions;
  };
return config;
};
```

Here is a repo to test it:
https://github.com/vltansky/tailwind-ng11

In this commit you can see all changes: https://github.com/vltansky/tailwind-ng11/commit/1e58ee15546557ceeb5b35ec33d22c9d84bb9cf0

Now `@apply` is working and all the imports (e.g ag-grid, ioniq) will work too.
The only thing to mention, that `@apply` will work only in global styles, not in components (do we need it on components level? it may slow down builds)

**Comment by sonicparke** [comment]
@vltansky THANK YOU!!!!

I've been fighting with getting tailwind to work in storybook in an nx repo with ng11. You're solution above made tailwind work in storybook.

**Comment by vltansky** [comment]
@sonicparke happy that it worked for you.
The solution in PR should work even better. Give it a try.
```js
module.exports = (config) => {
  const isProd = config.mode === "production";
  const tailwindConfig = require("./tailwind.config.js")(isProd);

  config.module.rules.map(rule=>{
    if(rule.use && rule.use.length > 0){
      rule.use.map(useLoader => {
        if(useLoader.options && useLoader.options.postcssOptions){
          const postcssOptions = useLoader.options.postcssOptions;
          useLoader.options.postcssOptions = (loader) => {
            const _postcssOptions = postcssOptions(loader);
            const autoprefixerIndex = _postcssOptions.plugins.findIndex(v=>v.postcssPlugin === 'autoprefixer');
            if(autoprefixerIndex){
              _postcssOptions.plugins.splice(autoprefixerIndex, 0, require('tailwindcss')(tailwindConfig));
            }
            return _postcssOptions;
          }
        }
        return useLoader;
      })
    }
    return rule;
  });
  return config;
};
```

**Comment by sonicparke** [comment]
> @sonicparke happy that it worked for you.
> The solution in PR should work even better. Give it a try.
> 
> ```js
> module.exports = (config) => {
>   const isProd = config.mode === "production";
>   const tailwindConfig = require("./tailwind.config.js")(isProd);
> 
>   config.module.rules.map(rule=>{
>     if(rule.use && rule.use.length > 0){
>       rule.use.map(useLoader => {
>         if(useLoader.options && useLoader.options.postcssOptions){
>           const postcssOptions = useLoader.options.postcssOptions;
>           useLoader.options.postcssOptions = (loader) => {
>             const _postcssOptions = postcssOptions(loader);
>             const autoprefixerIndex = _postcssOptions.plugins.findIndex(v=>v.postcssPlugin === 'autoprefixer');
>             if(autoprefixerIndex){
>               _postcssOptions.plugins.splice(autoprefixerIndex, 0, require('tailwindcss')(tailwindConfig));
>             }
>             return _postcssOptions;
>           }
>         }
>         return useLoader;
>       })
>     }
>     return rule;
>   });
>   return config;
> };
> ```

@vltansky Thanks, I followed the PR and pulled the final code out into my webpack config. There was the added complexity of Storybook needing the config but I got it all worked out. Thanks!
