### ISSUE TITLE
Webpack-merge is not a function

### ISSUE THREAD

**Issue by simonbarker** [ngneat/tailwind#16]
## I'm submitting a bug and a solution

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Compilation error: An unhandled exception occurred: merge is not a function
See "/private/var/folders/f1/t6fv0hmj5j50b4xqv7wy31wh0000gn/T/ng-dgN7Xj/angular-errors.log" for further details.

## Expected behavior

Should run on localhost:4200

## Minimal reproduction of the problem with instructions

install on an angular 11 prohect

## Solution

change:

`const merge = require('webpack-merge');` in webpacl.config.j to `const { merge } = require('webpack-merge');` assume merge is not longer the default export?

Either way this now compiles

## Environment

<pre><code>
Angular version: 11

**Comment by lhargil** [comment]
> ## I'm submitting a bug and a solution
> ```
> 
> [ ] Regression (a behavior that used to work and stopped working in a new release)
> [x] Bug report  
> [ ] Performance issue
> [ ] Feature request
> [ ] Documentation issue or request
> [ ] Support request
> [ ] Other... Please describe:
> ```
> 
> ## Current behavior
> Compilation error: An unhandled exception occurred: merge is not a function
> See "/private/var/folders/f1/t6fv0hmj5j50b4xqv7wy31wh0000gn/T/ng-dgN7Xj/angular-errors.log" for further details.
> 
> ## Expected behavior
> Should run on localhost:4200
> 
> ## Minimal reproduction of the problem with instructions
> install on an angular 11 prohect
> 
> ## Solution
> change:
> 
> `const merge = require('webpack-merge');` in webpacl.config.j to `const { merge } = require('webpack-merge');` assume merge is not longer the default export?
> 
> Either way this now compiles
> 
> ## Environment
> ```
> 
> Angular version: 11
> ```

Thank you for posting the solution. It works. :)

**Comment by nartc** [comment]
Probably due to webpack change. I’ll take a look as soon as possibl

**Comment by nartc** [comment]
Fix by the latest version
