### ISSUE TITLE
This breaks hmr in Angular 11

### ISSUE THREAD

**Issue by Bilal-io** [ngneat/tailwind#17]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

When adding ngneat/tailwind, hmr no longer works in Angular 11

## Expected behavior

hmr should still function the same way

## Minimal reproduction of the problem with instructions

- Install a new Angular 11 project `ng new test-hmr`
- Test that hmr works by running `ng serve --hmr` and changing something in a component. It should update without the whole page being refreshed
- Now add ngneat/tailwind by running `ng add @ngneat/tailwind`
- After the installation is done, run `ng serve --hmr`, make a change to a component, and the whole page will be refreshed every time.

## Environment

<pre><code>
Angular version: 11.0.1

Browser:
- [x] Edge version 87.0.664.30
 
For Tooling issues:
- Node version: 14.15.0
- Platform:  Windows

Others:
none
</code></pre>

**Comment by hiepxanh** [comment]
@Bilal-io I created an example repository and it still work sir https://github.com/hiepxanh/ng-eleven-tailwind

you can test it on here, just need update webpack merge code because it have new version

**Comment by Bilal-io** [comment]
I cloned and ran your repo, it worked fine. I am closing this issue.
