### ISSUE TITLE
merge is not a function with fresh ng add

### ISSUE THREAD

**Issue by hiepxanh** [ngneat/tailwind#20]
## I'm submitting a...

[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting --

## Current behavior

`
$ ng serve --hmr
Debugger listening on ws://127.0.0.1:57026/06b6f768-7ce8-46ed-8984-0a6a190d2252
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
See https://webpack.js.org/guides/hot-module-replacement for information on working with HMR for Webpack.
An unhandled exception occurred: merge is not a function
See "C:\Users\hiepx\AppData\Local\Temp\ng-QW9gFS\angular-errors.log" for further details.
Waiting for the debugger to disconnect...
`

## Expected behavior

running normally without error

## Minimal reproduction of the problem with instructions

```
- ng new ng-eleven
- ng add @ngneat/tailwind
- ng serve --hmr
```
## What is the motivation / use case for changing the behavior?

- Save the world

## Environment
```
Angular CLI: 11.0.2
Node: 14.15.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0

```

**Comment by elAndyG** [comment]
Looks like it will close #16 as well.

**Comment by nartc** [comment]
Fixed by the latest version
