### ISSUE TITLE
Can't resolve imports when using "stylePreprocessorOptions.includePaths"

### ISSUE THREAD

**Issue by eweap** [ngneat/tailwind#21]
Hello,

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. Create a nrwl nx workspace with an angular app
2. Run `nx add @ngneat/tailwind`
3. Add a path in:
```
...
"stylePreprocessorOptions": {
  "includePaths": ["scss"]
},
...
```
then import a file from this directory in your app `styles.scss`
4. Project failed to build

## Expected behavior

I expect file to be imported and project to build

## Minimal reproduction of the problem with instructions

I've created a repo for reproduction: https://github.com/eweap/tailwindcss-import-bug

</code></pre>

**Comment by intellix** [comment]
It seems the imports are all totally FUBAR for me. 

Had to change:
```
- @import '~@angular/material/theming';
+ @import '@angular/material/_theming.scss';
```

Libs from inside styles.scss:
```
- @import '~libs/ui-form/src/theming';
+ @import '../../../libs/ui-form/src/_theming.scss';
```

And then other libs trying to reference some helpers from another lib (probably needs refactoring) but doesn't work at all:
```
@import '/libs/ui/src/scss/_media.scss';
@import '../../../libs/ui/src/scss/_media.scss';
```

I did have the stylePreprocessorOptions exactly the same as above and had removed it. Surprised nobody else has mentioned issues with `~@angular/material/theming` yet but saw various complaints about it on Google

**Comment by nartc** [comment]
This is due to `postcss-imports` which is quite a mystery as of the moment. I will take a look into this when I have more time #15

**Comment by nartc** [comment]
I'll close this in favor of #15

**Comment by eweap** [comment]
@nartc  Thanks, I will follow #15 !
