### ISSUE TITLE
@ngneat/tailwind added as a dependency

### ISSUE THREAD

**Issue by vltansky** [ngneat/tailwind#22]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`@ngneat/tailwind` added to package.json dependencies
## Expected behavior
`@ngneat/tailwind` shouldn't be added to dependencies.

https://angular.io/guide/schematics-for-libraries#define-dependency-type

**Comment by nartc** [comment]
It's added to dependencies array with `ng add`. You'd need to remove the dependencies manually.
