### ISSUE TITLE
Docs: Example of the CSS file size reduction on a project like Material

### ISSUE THREAD

**Issue by intellix** [ngneat/tailwind#23]
**Is your feature request related to a problem? Please describe.**
After adding this and getting it to work within my own project I've noticed nothing has changed in regards to the output styles.css on a prod build. It'd be good to highlight what sort of gains are to be expected from a brand new project importing just material.

**Describe the solution you'd like**
It would be good to add documentation or an example with a table showing the before/after using this.

Some tests:
```
1) ng new tailwind
serve: 118 bytes | prod build: 0kb

2) ng add @angular/material (use https://material.angular.io/guide/theming#using-a-pre-built-theme SCSS recipe)
serve: 77.06kb | prod build: 67.74kb

3) ng add @ngneat/tailwind (remove tailwindcss SCSS refs)
serve: 336kb | prod build: 82.9kb
```

Example commit which adds material/tailwind: https://github.com/intellix/tailwind-material-test/commit/4e23ded6bb58aaa3ed1082d0241cf3f5347c5836

One thing I did notice is that if I keep the tailwindcss SCSS references it's about 9mb+ on a serve and most of it disappears on a production build, which makes me think the Purging only happens on Tailwind CSS classes?

I was expecting that after installing tailwind into the webpack process, it would purge all/most of Material as none of it is used/referenced in my HTML/TS

> What is PurgeCSS?
> When you are building a website, chances are that you are using a css framework like Bootstrap, Materializecss, Foundation, etc... But you will only use a small set of the framework and a lot of unused css styles will be included.

> This is where PurgeCSS comes into play. PurgeCSS analyzes your content and your css files. Then it matches the selectors used in your files with the one in your content files. It removes unused selectors from your css, resulting in smaller css files.

**Comment by nartc** [comment]
I'll add more documentations on various UI libraries in the near future. Thanks!

**Comment by nartc** [comment]
Close this in favor of #24 . Let's track this issue over there.

**Comment by intellix** [comment]
ok documentation sounds good but just curious if it was expected for tailwind to purge the unused Material CSS? Because out of the box it hasn't done anything and I can't see how extra configuration would help

**Comment by nartc** [comment]
Technically, Purge only looks at your code and won't look at node_modules code so it won't purge unused Angular Material CSS classes.

Now, it also depends on how Angular Material structures their styles for their components. Although I think it won't purge out of the box, I'm curious to see Angular Material CSS after build then maybe Purge can be configured to purge them.
