### ISSUE TITLE
'schematics_1.applyTemplates is not a function'

### ISSUE THREAD

**Issue by murphmar** [ngneat/tailwind#27]
![image](https://user-images.githubusercontent.com/4499601/101504515-e4462780-394d-11eb-979b-cd8e007b07cd.png)

Possibly relevant packages & versions:
 "@angular-devkit/core": "^10.0.0",
  "@angular/cdk": "^10.0.0",
  "@angular/core": "^10.0.4",
  "@angular/cli": "10.0.0",
  "@angular/compiler-cli": "^10.0.4",
  "@nrwl/workspace": "^10.0.1"

This fails whether using the angular CLI or the NX CLI for with the same error for each. It's not much to go off, so i'm not sure where to start. Has anyone come across this or anything similar?

**Comment by daboudii** [comment]
@murphmar how did you fix that ? 

I have the same problem in my project.
