### ISSUE TITLE
I am submitting a question for Webpack5

### ISSUE THREAD

**Issue by zhangjindong** [ngneat/tailwind#28]
## I am submitting a question for Webpack5。

<pre>
npm start

> ngx-build-plus-test@0.0.0 start /home/dong/learn/ngx-build-plus-test
> ng serve

An unhandled exception occurred: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.                                                        
 - configuration.output has an unknown property 'futureEmitAssets'. These properties are valid:
   object { assetModuleFilename?, auxiliaryComment?, charset?, chunkFilename?, chunkFormat?, chunkLoadTimeout?, chunkLoading?, chunkLoadingGlobal?, compareBeforeEmit?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, enabledChunkLoadingTypes?, enabledLibraryTypes?, enabledWasmLoadingTypes?, environment?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateGlobal?, hotUpdateMainFilename?, iife?, importFunctionName?, importMetaName?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine?, uniqueName?, wasmLoading?, webassemblyModuleFilename?, workerChunkLoading?, workerWasmLoading? }        
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.                                                                                       
See "/tmp/ng-tP57yg/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ngx-build-plus-test@0.0.0 start: `ng serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ngx-build-plus-test@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dong/.npm/_logs/2020-12-14T06_49_58_431Z-debug.log

</code></pre>

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem

## Environment

<pre><code>
    "webpack version": "5.10.0"
    "angular version":"11.0.4"

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by nartc** [comment]
Couple of things:
1. If you want to use Webpack 5, you need to use `yarn` instead of `npm`.
2. Can you provide a minimal reproduce?

**Comment by zhangjindong** [comment]
@nartc 
Hi,this is indeed webpack5, and it is installed through yarn
First it prompts "First it prompts "An unhandled exception occurred: Cannot find module'node-libs-browser'"
After installation, the above error is prompted

https://github.com/zhangjindong/ngx-build-plus-test.git

**Comment by nartc** [comment]
Can you try executing: delete config.output.futureEmitAssets before the return merge(...)?

**Comment by zhangjindong** [comment]
Yes, my problem was solved, but a new problem appeared.
I think that angular11 and webpage5 are still in an unstable stage.
thank you for your reply.

![image](https://user-images.githubusercontent.com/5567162/102768790-aa006f80-43bc-11eb-84db-eb4705a0ee7f.png)

**Comment by nartc** [comment]
Yeah it's still opt-in for Webpack5. Can we have this issue closed?
