### ISSUE TITLE
Error using @apply with Tailwind classnames containing /

### ISSUE THREAD

**Issue by tylermwatts** [ngneat/tailwind#35]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I used `@ngneat/tailwind` to add Tailwind to my Angular 10 project.

I am attempting to use a Tailwind classname with a `/` character like so
```css
/* header.component.scss */
@apply top-1/2;
```
This results in the following compiler error:
```
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Unexpected '/'. Escaping special characters with \ may help.
```
Attempting to escape the character like this:
```css
@apply top-1\/2;
```
Gives the following error:
```
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(56:2) app/header.component.scss The `top-1\/2` class does not exist, but `top-1/12` does. If you're sure that `top-1\/2` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

## Environment

<pre><code>
Angular version: 10.2.1

For Tooling issues:
- Node version: 14.15.3  
- Platform:  Mac, macOS Catalina

Others:
Editor: VS Code

</code></pre>
tailwind.config.js
```js
module.exports = (isProd) => ({
  prefix: '',
  purge: {
    enabled: isProd,
    content: ['./src/**/*.{html,ts}'],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        black: '#333333',
        white: '#ffffff',
        blue: {
          DEFAULT: '#0170bc',
          dark: '#004986',
          light: '#00a9e0',
          highlight: '#e6f1f8',
        },
        red: {
          DEFAULT: '#cc0000',
          highlight: '#ffe3e2',
        },
        green: '#118503',
        orange: {
          DEFAULT: '#f68621',
          dark: '#e35205',
        },
        gray: {
          60: '#505050',
          40: '#939496',
          15: '#d9d9d9',
          05: '#e4e4e4',
          01: '#f8f8f8',
        },
      },
      boxShadow: {
        'inner-gray-15': 'inset 0 0 3px 0.5px rgba(217, 217, 217, 1)',
        'inner-gray-40': 'inset 0px 1px 0px 0px rgba(147, 148, 150, 1)',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/ui')],
})
```

webpack.config.js
```js
const { patchPostCSS } = require('@ngneat/tailwind')

module.exports = (config) => {
  const isProd = config.mode === 'production'
  const tailwindConfig = require('./tailwind.config.js')(isProd)
  patchPostCSS(config, tailwindConfig, true)
  return config
}
```

**Comment by nartc** [comment]
Hi Tyler, I'm really not sure in this case :( I'm gonna keep this open to see if anyone knows a solution to this.

**Comment by vltansky** [comment]
@tylermwatts try upgrading to Angular 11.
Coudnt reproduce this issue in this demo: https://github.com/vltansky/tailwind-ng11

**Comment by tylermwatts** [comment]
> @tylermwatts try upgrading to Angular 11.
> Coudnt reproduce this issue in this demo: https://github.com/vltansky/tailwind-ng11

I'll give that a try and see if that's the issue. Thanks.

**Comment by tylermwatts** [comment]
Updating to Angular 11 solved the issue. Thanks for your help @vltansky!
