### ISSUE TITLE
Purge option is force enabled for production builds

### ISSUE THREAD

**Issue by 3fd** [ngneat/tailwind#46]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When explicitly setting `purge: { enabled: false }` in the tailwindConfig it will be overwritten to `true` for production builds.
This is a regression introduced in #39 

## Expected behavior

Custom purge options should be honored

## What is the motivation / use case for changing the behavior?

I use a cutom script to purge css after the build is complete

**Comment by nartc** [comment]
Closes with https://github.com/ngneat/tailwind/commit/2b7a48db2da79e75e350a90de73ad38928b3e976
