### ISSUE TITLE
readme fixes: nx

### ISSUE THREAD

**Issue by sinnrrr** [ngneat/tailwind#47]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Steps to reproduce
Current `readme.md` steps for Nx workspace

## Fix
Change Nx quickstart steps to just typing in terminal `nx add @ngneat/tailwind`, because in step, where the schematics are added the terminal utility has some issues like empty select fields and no y/n prompt.

**Comment by beeman** [comment]
Hi @sinnrrr, thanks for creating this issue.

Sadly, `nx add` is not yet support in all types of Nx workspaces, only on the ones working with the Angular CLI (those that have an `angular.json` file). There is [an issue](https://github.com/nrwl/nx/issues/4435) for this.

In the others, if you run `nx add @ngneat/tailwind`, you get an error:

```
$ nx add @ngneat/tailwind
Could not find project "@ngneat/tailwind"
```

This is because of how the `nx` command works. It will try to find the project with the name `@ngneat/tailwind` in the workspace.json, and run the `add` target on there.

**Comment by sinnrrr** [comment]
I must report, that `nx add @ngneat/tailwind` worked for me well! I think that this is because I preinstalled the @ngneat/tailwind with command `yarn add -D @ngneat/tailwind`, and after than ran `nx add`. Thanks for that quick response!

**Comment by nartc** [comment]
Glad that `nx add` worked for you. However, is there anything wrong with this `nx generate @ngneat/tailwind:nx-setup` that you're reporting?

**Comment by sinnrrr** [comment]
@nartc yeah, there are some issues. Let me show you how it looks like by screenshots:
![image](https://user-images.githubusercontent.com/25615887/104788803-d335d500-579b-11eb-956f-96226e785bcd.png)
![image](https://user-images.githubusercontent.com/25615887/104788823-e052c400-579b-11eb-82e1-99ecac084624.png)
![image](https://user-images.githubusercontent.com/25615887/104788836-ea74c280-579b-11eb-9014-fd8b125150e2.png)

**Comment by sinnrrr** [comment]
@beeman yeah, here is a screenshot of config files in my root
![image](https://user-images.githubusercontent.com/25615887/104788937-39225c80-579c-11eb-810c-ca6479c88d67.png)

**Comment by beeman** [comment]
> @beeman yeah, here is a screenshot of config files in my root
> ![image](https://user-images.githubusercontent.com/25615887/104788937-39225c80-579c-11eb-810c-ca6479c88d67.png)
> 
> I am currently using NestJS+Angular Nx Workspace

The reason in your case the `nx add` works, is because you are in an Angular CLI based project. This is the expected behavior.

**Comment by sinnrrr** [comment]
thanks for the quick issue resolution and great open source projects!
have a look at `nx generate @ngneat/tailwind:nx-setup` command problems; if my project wouldn't be angular-based, I'd have no opportunity to use @ngneat/tailwind in my project
