### ISSUE TITLE
nothing style imported after ng add @ngneat/tailwind.

### ISSUE THREAD

**Issue by chobijaeyu** [ngneat/tailwind#5]
hi. good day.
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

after ng add @ngneat/tailwind no style imported.

## Expected behavior

expected tailwindcss imported.

## Minimal reproduction of the problem with instructions

1. ng new myapp
2.ng add  @angular/pwa
   ng add  @scullyio/init
   ng add @ngneat/tailwind
3.edit html 
```
<header>
  <nav class="flex justify-between items-center  px-8 bg-opacity-50">
    <div class="flex gap-4 flex-1">
      <div>
        <a [routerLink]="[ '/products' ]">PRODUCTS</a>
      </div>
      <div>
        <a [routerLink]="[ '/news' ]">NEWS</a>
      </div>
    </div>
    <div class="flex-1">
      <img src="assets/icons/icon-72x72.png" alt="company-logo">
    </div>

    <div class="flex gap-4">
      <div>
        <a [routerLink]="[ '/contact' ]">CONTACT</a>
      </div>
      <div>
        <a [routerLink]="[ '/about' ]">ABOUT</a>
      </div>
    </div>
  </nav>
</header>
```

4.ng s
![2020-09-13 16 26 30](https://user-images.githubusercontent.com/25117318/93012790-f417cf00-f5dd-11ea-944c-dab1a443c1bd.png)

## What is the motivation / use case for changing the behavior?

I try to using Tailwind via CDN

add `  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">` to index.html
![2020-09-13 16 32 26](https://user-images.githubusercontent.com/25117318/93012888-be271a80-f5de-11ea-87a8-c72c90f0d335.png)

it's works by use cdn way.

## Environment

<pre><code>
Angular CLI: 10.0.8
Node: 14.7.0
OS: darwin x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.0
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

Browser:
- [X] Chrome (desktop) version  85.0.4183.102
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>
tailwind.config.js:

```
module.exports = (isProd) => ({
    prefix: '',
    future: {
      removeDeprecatedGapUtilities: true,
      purgeLayersByDefault: true
    },
    purge: {
      enabled: isProd,
      content: ['**/*.html', '**/*.ts']
    },
    theme: {}
});
```

webpack.config.js:

```
const merge = require('webpack-merge');

module.exports = (config) => {
  const isProd = config.mode === "production";
  const tailwindConfig = require("./tailwind.config.js")(isProd);

  return merge(config, {
    module: {
      rules: [
        {
          test: /\.sass$/,
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              ident: 'postcss',
              syntax: 'postcss-sass',
              plugins: [
                require('postcss-import'),
                require('tailwindcss')(tailwindConfig),
                require('autoprefixer'),
              ]
            }
          }
        }
      ]
    }
  });
};
```
angular.json:

```
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "bplaboHomePage:build",
            "customWebpackConfig": {                                             <--- add by myself
              "path": "webpack.config.js"                                       <--- add by myself
            }
          },
          "configurations": {
            "production": {
              "browserTarget": "bplaboHomePage:build:production"
            }
          }
        },
```

**Comment by nartc** [comment]
Are you using CSS or SCSS (SASS) for your application?

**Comment by chobijaeyu** [comment]
@nartc yes.

I tried use styles.sass.

```
@import 'tailwindcss/base'           <---- it't not works.
@import 'tailwindcss/utilities'        <---- it't not works.
@import url('https://fonts.googleapis.com/css2?family=Pacifico&family=Sawarabi+Mincho&display=swap')   <---- it't not works.

$primary: #b7b7a4
$font-color:#34495E
/* You can add global styles to this file, and also import other style files */
.bp-gray-bg                                                  <---- it't works.
    background-color: #e2e1e2

.bp-primary-bg
    background-color: #b7b7a4b5
```

seem to can't import anything.
google font can't be imported also.

**Comment by nartc** [comment]
@chobijaeyu no error?

**Comment by chobijaeyu** [comment]
@nartc no error

**Comment by nartc** [comment]
@chobijaeyu I have just investigated and looks like `postcss-sass` does not support `@import` syntax (or `@use` for that matter). Would having to switch to `scss` a deal breaker for you? Because unfortunately and sorry to say, this is a limitation to the `postcss-sass` itself and there's really nothing we can do about it.

**Comment by chobijaeyu** [comment]
@nartc I see . thanks for your time.
