### ISSUE TITLE
Feature: support for custom-webpack users

### ISSUE THREAD

**Issue by vltansky** [ngneat/tailwind#51]
Right now schematics will fail if there is existing `webpack.config.js` or `tailwind.config.js`.

I think we should start from writing instruction of manual integration:
- npm install @ngneat/tailwind
- npm install postcss (postcss 8 needed until angular 11.1.0)
- import `patchPostCSS` and `tailwindConfig` in `webpack.config.js`
- pass parameters to `patchPostCSS`

Put it to readme and also as a separate article or something, so until better solution will be found we can point users there (just console.log message with a link if there is webpack config)

Also, we should consider if there is a way to add needed code to the already existing `webpack.config.js`

**Comment by nartc** [comment]
Yes. A manual set of steps for existing webpack.config would be great.

For schematics, I think we need a separate schematics called "migrate" or something like that to target specific users with exisitng webpack config since we would need to ask where they put their configs.

**Comment by vltansky** [comment]
We don't need to ask where they put it. We know it from angular.json

**Comment by nartc** [comment]
Yup yup you're right. Then we'll be able to support this.

**Comment by nartc** [comment]
Do we need to consider how the users use custom-webpack? Do they patch config like we do? or they return a merged config? Would that affect how we edit webpack.config for them?

Also it just came to me that the webpack path in angular.json (or workspace.json) could just be an index file where they return different config files based on the process.env (our current work project does this).

**Comment by vltansky** [comment]
You are right. Seems to me better not to modify existing config. Guess will be better just point to instruction of manual setup.

**Comment by vltansky** [comment]
@nartc 
instead of ```
ERROR! tailwind.config.js already exists.
ERROR! webpack.config.js already exists.
The Schematic workflow failed. See above.
```

we should show a message with manual instruction. Seems like schematics don't have built-in support for custom messages...?

**Comment by nartc** [comment]
Maybe we can try/catch this? https://github.com/ngneat/tailwind/blob/49928e0a479af7e60fb4301748c0012a107a2cea/libs/tailwind/src/utils/add-config-files.ts#L13

**Comment by vltansky** [comment]
Tried. I don't understand why, but it's not catching an error here.
maybe this can help?
https://stackoverflow.com/questions/48957132/how-to-overwrite-file-with-angular-schematics
`if (tree.exists(fileEntry.path)) return null;` console log here?
