### ISSUE TITLE
Documentation: Using !important will result in a critical build error

### ISSUE THREAD

**Issue by AlexanderOpran** [ngneat/tailwind#59]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using !important after in an @apply statement will result in module build errors.

## Expected behavior

I should still be apple to use !important without build errors.

## Minimal reproduction of the problem with instructions

Here is a repo (ngneat branch) that reproduces this issue:  https://github.com/AlexanderOpran/angular-tailwind-debug/tree/ngneat

## Environment

<pre><code>
Angular version: 11.1
</code></pre>

**Comment by vltansky** [comment]
I've opened a PR to your repo.
Check it 
https://github.com/AlexanderOpran/angular-tailwind-debug/pull/1

**Comment by vltansky** [comment]
according to https://tailwindcss.com/docs/functions-and-directives#apply:

Note that if you're using Sass/SCSS, you'll need to use Sass' interpolation feature to get this to work:
```css
.btn {
  @apply font-bold py-2 px-4 rounded #{!important};
}
```

**Comment by AlexanderOpran** [comment]
> according to https://tailwindcss.com/docs/functions-and-directives#apply:
> 
> Note that if you're using Sass/SCSS, you'll need to use Sass' interpolation feature to get this to work:
> 
> ```css
> .btn {
>   @apply font-bold py-2 px-4 rounded #{!important};
> }
> ```

Hey, thanks, I was using the interpolation in my vue project with tailwind. Thing is, until now everything worked without it in Angular, meaninf that I was able to use important without interpolation with no issues. What exactlt has changed? Thanks 😂

**Comment by vltansky** [comment]
I don't know. But I can't use it too.
Maybe Angulars `node-sass` -> `dart-sass` migration?

**Comment by nartc** [comment]
@AlexanderOpran  @vltansky  probably when we switch over to patching Angular's PostCSS?! I remember using `!important` without the interpolation when we use the "merge" approach.

Alex, can you confirm that using interpolation works now? If yes, can we close this issue? Do you see any action item that is needed? maybe a note in README?

**Comment by AlexanderOpran** [comment]
Interpolation works now, I guess you can close this issue. As far as action items go, perhaps update the documentation with a note because previously without the PostCSS patch important was working without interpolation. 

Any chance to make the PostCSS patch also use merge and still work?😺

**Comment by nartc** [comment]
@AlexanderOpran unfortunately, not that I know of (maybe @vltansky might know of a way). As far as I know, it's one **or** the other. "merging approach" uses `webpack-merge` to merge a new `rule` to the current **webpack config** which **does not** take into consideration of all other rules from the existing Angular CLI's webpack config in terms of handling preprocessors (SCSS, LESS etc...). "patching" allows us to rely on AngularCLI.

**Comment by vltansky** [comment]
I don't know a way to make it work. And actually, I see it as not expected behavior when it was possible to use important without interpolation and now as expected, well documented by tailwind behavior.
I think it will be enough to add this link to readme: https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus
