### ISSUE TITLE
Could not find project "@ngneat/tailwind" when running in an nx workspace

### ISSUE THREAD

**Issue by lhargil** [ngneat/tailwind#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running the add schematics commands results in the following errors when used on a newly-created NX workspace. 

1. `nx add @ngneat/tailwind` = Could not find project "@ngneat/tailwind"

2. `ng add @ngneat/tailwind` = The add command requires to be run in an Angular project, but a project definition could not be found.

**For clarification and as pointed out below, this does not work in an NX workspace using the NX cli.** 

## Expected behavior

TailwindCSS is added correctly.

## Minimal reproduction of the problem with instructions

1. Create new NX latest workspace, empty and CLI used is NX: `npx create-nx-workspace@latest`

2. Add new Angular app: `nx g @nrwl/angular:app sample-app --routing --style=scss`

3. Add @ngneat/tailwind: `nx add @ngneat/tailwind`

## What is the motivation / use case for changing the behavior?

I want to use TailwindCSS for a collection apps in an NX workspace.

## Environment

<pre><code>
Angular version: 10.0.0

Browser:
- [] Chrome (desktop) version XX
- [] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Windows

Others:

</code></pre>

By the way, this schematics and the one before it works in an Angular workspace. Thank you for the great work.

**Comment by DominikPieper** [comment]
Small addition. In an Nx workspace with ng-cli instead of nx-cli it works.

**Comment by lhargil** [comment]
> Small addition. In an Nx workspace with ng-cli instead of nx-cli it works.

Yes indeed, @DominikPieper. Will clear that up in my original post.

**Comment by nartc** [comment]
Thanks for reporting. I'll take a look as soon as possible.

**Comment by nartc** [comment]
@lhargil I took a closer look at a Nx Workspace support for Angular schematics. Unfortunately, . `@ngneat/tailwind` greatly depends on Angular Schematics utilities and there are so many discrepancies between Angular and Nx schematics utilities:

- `getWorkspace()`: Angular's `getWorkspace()` is a synchronous function where as Nx's is an asynchronous.
- `getProjectFromWorkspace()`: There's no equivalent in Nx Workspace utilities. Looking through Nx's source code for how they get the `project` from the `workspace`, it's just `workspace.projects.get(projectName)`. 
- `getTargetsByBuilderName()`: There's no equivalent in Nx Workspace utilities. This method is to look for all records under `architect` that current have `@angular-devkit/build-angular:browser` or `@angular-devkit/build-angular:dev-server` to replace them with the ones from `@angular-builders/custom-webpack:*`. 

With that in mind, I decided to **not** support pure Nx Workspace with `workspace.json` for now. Please consider using Angular CLI powered Nx workspace instead (with `angular.json`). However, I will keep this request in mind.

**Comment by lhargil** [comment]
> @lhargil I took a closer look at a Nx Workspace support for Angular schematics. Unfortunately, . `@ngneat/tailwind` greatly depends on Angular Schematics utilities and there are so many discrepancies between Angular and Nx schematics utilities:
> 
> * `getWorkspace()`: Angular's `getWorkspace()` is a synchronous function where as Nx's is an asynchronous.
> * `getProjectFromWorkspace()`: There's no equivalent in Nx Workspace utilities. Looking through Nx's source code for how they get the `project` from the `workspace`, it's just `workspace.projects.get(projectName)`.
> * `getTargetsByBuilderName()`: There's no equivalent in Nx Workspace utilities. This method is to look for all records under `architect` that current have `@angular-devkit/build-angular:browser` or `@angular-devkit/build-angular:dev-server` to replace them with the ones from `@angular-builders/custom-webpack:*`.
> 
> With that in mind, I decided to **not** support pure Nx Workspace with `workspace.json` for now. Please consider using Angular CLI powered Nx workspace instead (with `angular.json`). However, I will keep this request in mind.

Thank you for taking a look, @nartc. I understand where you're coming from and it is fine by me. In the meantime, I got by, by manually adding the changes to the nx project, works as intended. 👍

**Comment by nartc** [comment]
Closing. Might revisit
