### ISSUE TITLE
Workflow fails when adding ngneat/tailwind to multiple projects.

### ISSUE THREAD

**Issue by TryHardDood** [ngneat/tailwind#61]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

- `ng add @ngneat/tailwind --project application-1`
  - It successfully adds tailwind to *application-1*
- `ng add @ngneat/tailwind --project application-2`
  - It fails to add tailwind to *application-2* because _webpack.config.js_ and _tailwind.config.js_ already exists.

* It's the same for NX workspaces too.

## Expected behavior

- `ng add @ngneat/tailwind --project application-1`
  - It successfully adds tailwind to *application-1*
- `ng add @ngneat/tailwind --project application-2`
  - It should add tailwind to *application-2* and ignore the already existing _webpack.config.js_ and _tailwind.config.js_.

**Comment by FanchGadjo** [comment]
This schematic has been a great tool, thank you all !

I am getting the same behaviour.
My work-around at the moment is to delete those two files.

**Comment by TryHardDood** [comment]
> This schematic has been a great tool, thank you all !
> 
> I am getting the same behaviour.
> My work-around at the moment is to delete those two files.

Yeah I know, however it's getting annoying after the 5th application :D

**Comment by nartc** [comment]
Thanks for reporting!

**Comment by beeman** [comment]
I guess the simplest fix is to add a check [here](https://github.com/ngneat/tailwind/blob/main/libs/tailwind/src/utils/add-config-files.ts#L21) to see if these files exist, and if so skip the generation? 

If that's the case, I'm happy to take a stab at that.

**Comment by nartc** [comment]
@beeman yup most likelt a try catch there would work
