### ISSUE TITLE
Add an option to pass plugins to patchPostCSS in webpack.config.js

### ISSUE THREAD

**Issue by TryHardDood** [ngneat/tailwind#62]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

It would be cool to pass an array of postcss plugins to `patchPostCSS` and append them after tailwind. (As an optional argument)

**Comment by nartc** [comment]
@TryHardDood We tend not to try to cover for things outside of Tailwind because patchPostCSS from ngneat/tailwind targets very specific part of AngularCLI’s webpack config to add Tailwind to that. 

What plugins are you trying to add? Would calling “patchPostCSS()” again and pass in your plugin work?

**Comment by TryHardDood** [comment]
I'm trying to add plugins like `postcss-preset-env` and `postcss-css-variables`.

**Comment by vltansky** [comment]
@TryHardDood I'm working on this kind of plugin. It's still in development stage, but you can give it a try:
https://github.com/vltansky/patchAngularPostCSS

`npm i patch-angular-postcss -D`
in `webpack.config.js`:
```js
const { patchAngularPostCSS } = require("patch-angular-postcss");


module.exports = (config) => {
  patchAngularPostCSS({
    webpackConfig: config,
    addPlugins: [
      require("postcss-preset-env"),
      require("postcss-css-variables")
    ],
  });
  return config;
};
```

together with tailwind it will look like:

```js
const { patchPostCSS } = require("@ngneat/tailwind");
const tailwindConfig = require("./tailwind.config.js");

module.exports = (config) => {
  patchPostCSS(config, tailwindConfig);
  patchAngularPostCSS({
    webpackConfig: config,
    addPlugins: [
      require("postcss-preset-env"),
      require("postcss-css-variables")
    ],
  });
  return config;
};
```

Just to mention I do not recommend trying to add tailwind using patchAngularPostCSS, as ngneat/tailwind have extra optimizations under the hood, so tailwind will work seamlessly with Angular.

@nartc I do think that even if we decide to not simplify postcss function, we should rename it to `addTailwindCSS`, as the name now is giving the wrong expectation from it.

**Comment by TryHardDood** [comment]
@vltansky Looks great! I'll give this a try.

**Comment by nartc** [comment]
@vltansky I agree with renaming `patchPostCSS` to `addTailwindCSS`. 

> Just to mention I do not recommend trying to add tailwind using patchAngularPostCSS, as ngneat/tailwind have extra optimizations under the hood, so tailwind will work seamlessly with Angular.

Hm...would it make sense to use `patchPostCSS()` for other plugins then?

**Comment by vltansky** [comment]
@nartc for most of them I think yes.
By extra optimisations, I mean right now it's a pr with postcss plugin for dark mode. But using ngneat/tailwind will guarantee you that you will get Relevant fixed under the hood for new angular / tailwind versions. While using patchAngularPostcss() mean that it's up to you to maintain it.

**Comment by nartc** [comment]
Can we close this? @vltansky  @TryHardDood

**Comment by TryHardDood** [comment]
Sure. I support the idea of renaming the function to addTailwindCSS
