### ISSUE TITLE
Add Tailwind to Second Project in Nx Workspace

### ISSUE THREAD

**Issue by pjlamb12** [ngneat/tailwind#64]
**Is your feature request related to a problem? Please describe.**
I added @ngneat/tailwind to project-a in my Nx workspace and it worked perfectly. Then I tried to add it to a second project, project-b, using the nx generate command. The command failed though because the tailwind.config.js file already existed.

**Describe the solution you'd like**
I think that the schematic should either allow a tailwind.config.js and webpack.config.js file to exist when the schematic is run, or have a second schematic that just adds it to a second project but doesn't need to add the config files.

**Describe alternatives you've considered**
Instead I had to look in the angular.json at project-a and make the corresponding changes to project-b

**Comment by vltansky** [comment]
Looks the same as #61

**Comment by nartc** [comment]
duplicate with #61
