### ISSUE TITLE
Dependency issues with latest version

### ISSUE THREAD

**Issue by micobarac** [ngneat/tailwind#67]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
[3/4] Linking dependencies...
warning " > postcss-ng-tailwind-in-components@0.0.2" has unmet peer dependency "postcss@^8.2.4".
warning " > tailwindcss@2.0.2" has unmet peer dependency "autoprefixer@^10.0.2".
warning " > tailwindcss@2.0.2" has unmet peer dependency "postcss@^8.0.9".
warning "tailwindcss > postcss-nested@5.0.3" has unmet peer dependency "postcss@^8.1.13".
```

## Expected behavior

No dependency warnings

## Minimal reproduction of the problem with instructions

Create new `Angular 11.1.1` app
Add `@ngneat/tailwind` schematics

Adding the missing `postcss` and `autoprefixer` dependencies manually solved the problem.

## What is the motivation / use case for changing the behavior?

No dependency warnings

## Environment

<pre><code>
Angular version: X.Y.Z
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.2
Node: 15.7.0
OS: linux x64

Angular: 11.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v15.7.0
- Platform:  Ubuntu
</code></pre>

**Comment by vltansky** [comment]
cant reproduce: 
```
$ ng add @ngneat/tailwind
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Would you like to enable dark mode? none
? Would you like to use tailwind directives & functions in component styles? (might increase build time) No
? What @tailwindcss plugins do you want to enable?
    ✅️ Added postcss-ng-tailwind-in-components@0.0.3
    ✅️ Added @angular-builders/custom-webpack@11.0.0
    ✅️ Added tailwindcss@2.0.2
    ✅️ Installed dependencies
CREATE tailwind.config.js (257 bytes)
CREATE webpack.config.js (241 bytes)
UPDATE package.json (1359 bytes)
UPDATE angular.json (3740 bytes)
UPDATE src/styles.css (175 bytes)
✔ Packages installed successfully.
```

**Comment by micobarac** [comment]
@vltansky

please add some dependency after that, for instance:

`yarn add chart.js`

You'll get the warnings:

```
[3/4] Linking dependencies...
warning " > tailwindcss@2.0.2" has unmet peer dependency "autoprefixer@^10.0.2".
warning " > tailwindcss@2.0.2" has unmet peer dependency "postcss@^8.0.9".
warning "tailwindcss > postcss-nested@5.0.3" has unmet peer dependency "postcss@^8.1.13".
```

**Comment by micobarac** [comment]
Btw, I love your project, it's awesome!!! :D

**Comment by vltansky** [comment]
I see. It reproduces for me too with yarn, but not with npm:

```
$ npm i chart.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\chokidar\node_modules\fsevents):       
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ chart.js@2.9.4
added 4 packages from 7 contributors and audited 1657 packages in 11.952s

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

yarn:
```
[3/4] Linking dependencies...
warning " > tailwindcss@2.0.2" has unmet peer dependency "autoprefixer@^10.0.2".
warning " > tailwindcss@2.0.2" has unmet peer dependency "postcss@^8.0.9".
warning "tailwindcss > postcss-nested@5.0.3" has unmet peer dependency "postcss@^8.1.13".
```

@micobarac but everything works, right? It's only a warning that appears after yarn is running?

@nartc not sure what to do about it? Although yarn sees it as unmet peer dependency, in fact, it's existing and we're injecting Tailwind into angulars PostCSS

**Comment by micobarac** [comment]
@vltansky everything works just fine. It is just a bunch of warnings. It seems as though that `yarn` requires those dependencies to be set explicitly.

**Comment by nartc** [comment]
@micobarac this would be a weird issue if it happens just now. Looks like the warnings say `tailwindcss` is missing peer dependencies but `tailwindcss@2.0.2` was released 2 months ago which does not really make sense if the warning starts happening now.

**Comment by beeman** [comment]
As far as I know that warning has appeared for a while now.

**Comment by nartc** [comment]
I would consider this an issue on the Tailwind side of things instead of ngneat/tailwind. What do you guys think?

**Comment by lacolaco** [comment]
I hit the same situation. Today I executed the commands below and `postcss@8` is missing. 

```
$ npx @angular/cli@latest new my-app
$ cd my-app
$ npx ng add @ngneat/tailwind@latest
$ npm run build
```

```
Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
```


```
$ npx ng version

Angular CLI: 11.1.2
Node: 12.18.3
OS: darwin x64

Angular: 11.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
```

**Comment by vltansky** [comment]
@lacolaco what is `@angular-builders/custom-wepback` version?

**Comment by lacolaco** [comment]
@vltansky Thank you for a quick response!

```
$ cat node_modules/@angular-builders/custom-webpack/package.json
{
  "name": "@angular-builders/custom-webpack",
  "version": "11.0.0",
  "description": "Custom webpack builders for Angular build facade. Allow to modify Angular build configuration without ejecting it",
  "main": "dist/index.js",
  "files": [
    "dist",
    "builders.json"
  ],
...
```

Repository is this: https://github.com/lacolaco/ngneat-tw-issues-67-repro

**Comment by MatthewAlner** [comment]
Same issue with a fresh `ng new some-app-name`

"@angular-builders/custom-webpack": "11.0.0"

I picked `scss` and am using `yarn` in the initial setup if that makes a difference

`yarn add --dev postcss@8`

Fixed it for me
