### ISSUE TITLE
feat(@angular-devkit/build-angular): detect and use tailwindcss 

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/tailwind#70]
https://github.com/angular/angular-cli/commit/73b409881f71a8235769a345356dcde3c568d0c3

**Comment by DominikPieper** [comment]
https://twitter.com/angular/status/1359736376581840896?s=19

It's landed with 11.2

**Comment by beeman** [comment]
Awesome to see official support for Tailwind in Angular! This means we don't need to rely on a non-standard builder and no webpack config in the project root! 🎉

I think `@ngneat/tailwind` can still add value for apps built with Angular 11.2 though. For instance, by adding the tailwind imports to the css file (Angular doesn't do that for you), and installing plugins and configure dark mode.  

Additionally it's probably good to try and keep supporting older Angular versions (probably 9+).

**Comment by DominikPieper** [comment]
It adds value definitively, and just the build config is easier for the newer version. Everything else is great to start fast.

**Comment by Bilal-io** [comment]
Where does this repo go from here?

**Comment by vltansky** [comment]
As @beeman said we just won't need to add custom webpack config and modify Angulars build anymore.

Guess we need to give Angular some time before releasing new version.
As `@angular-devkit/build-angular` [still not published](https://twitter.com/mgechev/status/1359892063379066880) + `@angular-builders/custom-webpack` should also be updated to support Tailwind.

**Comment by nartc** [comment]
As mentioned here by other folks, we'll try to discuss and come up with a plan forward for this repository when I get back from my parental leave. Thanks for all the supports and sorry for the delay in the mean time.

**Comment by nartc** [comment]
Closes with #79
