### ISSUE TITLE
Purge not working

### ISSUE THREAD

**Issue by tomalaforge** [ngneat/tailwind#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I build my project in production, my style.css is not purged
However, when I set purge { enabled: true } in my tailwind.config.ts, the style.css is well purged

## Expected behavior

my style.css should be purged if I don't set any value to purge in taiwing.config.ts

## Minimal reproduction of the problem with instructions

ng new my-projet (v11.2.1)
ng add  @ngneat/tailwind
(no dark mode, patchComponentsStyles to true and no plugin)
ng build --prod

## Environment

Angular version: 11.2.1

**Comment by CSalih** [comment]
Hello tomalaforge, did you set the `NODE_ENV` to `production`? 
Try it with `NODE_ENV=production ng build --prod`
For more information please read https://tailwindcss.com/docs/optimizing-for-production#basic-usage

**Comment by tomalaforge** [comment]
Thanks @CSalih , this is working perfectly. 
Maybe a note in a README can be interesting.

**Comment by CSalih** [comment]
@tomalaforge you are welcome.
Reading the docs of `Tailwind - Optimizing for Production` is general a good idea. Adding a hint to read the docs would be a great idea.
Link: https://tailwindcss.com/docs/optimizing-for-production

**Comment by vltansky** [comment]
This happens due to the conflict of `@ngneat/tailwind` with Angular > 11.2.0 that has built-in support tailwind without purge functionality (https://github.com/angular/angular-cli/issues/20015).

I'd better opt-out from angular support until bugs fixed.
To use `@ngneat/tailwind` over angular built-in Tailwind support:
1. Rename `tailwind.config.js` to `tailwind.js`
2. Change the imports in `webpack.config.js`

**Comment by tomalaforge** [comment]
thanks @vltansky. I was looking for a similar issue with no success. Thanks for the link and for solution to opt-out from angular.
