### ISSUE TITLE
Unable to install tailwind to angular project

### ISSUE THREAD

**Issue by abhishekdana1999** [ngneat/tailwind#89]
While installing ng tailwind  to an angular project I am getting an error 
Command failed: [object Promise] rm @ngneat/tailwind
/bin/sh: 1: [object: not found

This don't use to happen previously with the latest update I am getting this error from today morning.

**Comment by waynegakuo** [comment]
Getting the same issue as well right now

**Comment by waynegakuo** [comment]
Hello @abhishekdana1999 
I was having the same issue but you need to update your Angular CLI
Reference: https://github.com/ngneat/tailwind/issues/88#issuecomment-814841130

**Comment by abhishekdana1999** [comment]
Yes

> Getting the same issue as well right now

**Comment by waynegakuo** [comment]
Hello @abhishekdana1999 
I was having the same issue but you need to update your Angular CLI
Reference: https://github.com/ngneat/tailwind/issues/88#issuecomment-814841130

**Comment by abhishekdana1999** [comment]
Thank the issue got solved with updating the angular cli version

**Comment by waynegakuo** [comment]
Great. You could close the issue then if it's resolved.
