### ISSUE TITLE
ng add fails

### ISSUE THREAD

**Issue by heddendorp** [ngneat/tailwind#90]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ng add @ngneat/tailwind@latest` fails with

```
ng add @ngneat/tailwind@latest
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
? Would you like to enable Tailwind JIT (preview feature)? Yes
? Would you like to enable dark mode? none
? What @tailwindcss plugins do you want to enable?
'[object' is not recognized as an internal or external command,
operable program or batch file.
Command failed: [object Promise] rm @ngneat/tailwind
'[object' is not recognized as an internal or external command,
operable program or batch file.
```

## Expected behavior
The command works

## Minimal reproduction of the problem with instructions
run `ng add @ngneat/tailwind@latest`

## Environment

<pre><code>
Angular CLI: 11.1.4
Node: 12.19.1
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cdk                    11.2.8
@angular/cli                    11.1.4
@angular/fire                   6.1.4
@angular/material               11.2.8
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.7
typescript                      4.1.5

For Tooling issues:
- Node version: 12.19.1 
- Platform:  Windows 

Others:

</code></pre>

**Comment by nartc** [comment]
Please make sure you’re on Angular 11.2+ and AngularCLI version is 11.2+. 

Although, the error message should be clearer.

**Comment by vltansky** [comment]
@nartc probably it failed at versions checking. Maybe try..catch there would help?

```

? Would you like to enable dark mode? none
? What @tailwindcss plugins do you want to enable?

    Detected AngularCLI version is 11.1.4 which does not support TailwindCSS natively.
    Please run "ng add @ngneat/tailwind@6" for Custom Webpack support.
```

@heddendorp do you have a more detailed stack?
