### ISSUE TITLE
Nx detect production build failed

### ISSUE THREAD

**Issue by pascalmann** [ngneat/tailwind#92]
Hi,

The production build detection doesn't work with **Nx**.
The guessProductionMode() function returns false when I run ```ng build --prod```.

The joined process.argv is:
```c:\\program files\\nodejs\\node.exe c:\\users\\...\\node_modules\\@nrwl\\cli\\lib\\run-cli.js run project:build:production```

So the constant in **guessProductionMode()** should be:
```
const isBuild = argv.includes(' build') || argv.includes(':build:production');
```

**Comment by nartc** [comment]
cc @vltansky

**Comment by beeman** [comment]
I guess having `const isBuild = argv.includes('build')` should be enough to cover both bases?

**Comment by vltansky** [comment]
@beeman checking just for `build` can trigger many wrong cases, for example, `build` in folder names and etc.

As an example:
`c:\\program files\\nodejs\\node.exe c:\\users\\...\\my_project_build_name\\node_modules\\@nrwl\\cli\\lib\\run-cli.js run project:build:production`

**Comment by beeman** [comment]
Maybe the easiest is to accept a parameter in `guessProductionMode()` and default it to what we have for now?

Seems like a more flexible way than try to figure out the edge cases :)
