### ISSUE TITLE
An unhandled exception occurred: addTailwindPlugin is not a function

### ISSUE THREAD

**Issue by rudyhadoux** [ngneat/tailwind#96]
Hi,

Has someone already had this problem ?
**An unhandled exception occurred: addTailwindPlugin is not a function.**
With ng add @ngneat/tailwind in a Angular 11 web app.

**Comment by rudyhadoux** [comment]
The problem disappears with a brand new Angular 11 app.
So I close.

**Comment by harvanchik** [comment]
I updated to version 7.0.3, and I am now getting this same error.

I cannot simply created a new project.

**Comment by rudyhadoux** [comment]
I took configuration files from ng new app + ng add @ngneat/tailwind.
And it works.

**Comment by harvanchik** [comment]
@rudyhadoux Which config files did you copy over exactly?

**Comment by rudyhadoux** [comment]
All files over SRC.

**Comment by harvanchik** [comment]
Not really a solution.  Who knows how many customizations I have made to those files over the months.  I cannot just replace them with fresh files.

**Comment by rudyhadoux** [comment]
It is not a perfect solution. Indeed.

**Comment by harvanchik** [comment]
Thanks for trying.  I'll wait to hear from the owner of the repo.

**Comment by harvanchik** [comment]
For now, I've downgraded back to version 6.0.3.  Still working in that version.

**Comment by rudyhadoux** [comment]
It's a problem of configuration change with the new version.

**Comment by rudyhadoux** [comment]
It seems to be a problem with yarn install.
Not with npm.

**Comment by harvanchik** [comment]
I used NPM though (not yarn), so I don't think so.

**Comment by harvanchik** [comment]
Any way for you to re-open this or does the repo owner have to do that?

**Comment by gast** [comment]
Looks like in old version has been used customWebpackConfig. Removing a "customWebpackConfig" block from the angular.json helps solve a problem.

**Comment by nateiorg** [comment]
As @gast mentioned, the error comes from utilizing custom webpack for builds. Since Angular 11.2.x supports TW out of the box, you just need to change your builders back to core:

```
"build": {
          "builder": "@angular-devkit/build-angular:browser",
```

```
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
```

Everything works for me after upgrading and swapping my builders back to core. Hope this helps.

**Comment by harvanchik** [comment]
@nateiorg Thanks for sharing.  I think we can close this issues now. @rudyhadoux
